# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Release Cryptonite on test.pypi

on:
  release:
    types: [ published ]

jobs:
  publish-package-pipy:
    name: Publish Cryptonite on test.pypi
    runs-on: ubuntu-latest
    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: cryptonite-${{ github.ref_name }}

      - name: Extract package
        run: tar -xf cryptonite-*/cryptonite-*.tar.xz --strip-components=1

      - name: Generate requirements.txt
        # Twine is one of the packages that can be used to upload packages to PyPI
        run: echo 'twine>=4' > requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache-dependency-path: requirements.txt
          cache: pip

      - name: Install twine
        run: python3 -m pip install -r requirements.txt

      - name: Upload package to test.pypi
        env:
          TWINE_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
        run: python3 -m twine upload --repository testpypi *cryptonite*.{whl,tar.gz}

  download-package:
    name: Download Cryptonite from test.pypi
    needs: publish-package-pipy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-rc"]
      fail-fast: false

    container: python:${{ matrix.python-version }}

    steps:
      - name: Download Cryptonite from PyPI
        run: |
          python3 -m pip install \
            --extra-index-url https://test.pypi.org/simple/ \
            "2022-sbi-ci-workflow-cryptonite==${{ github.ref_name }}"

      - name: Check Cryptonite version
        run: cryptonite --version


  make-package-for-gh-release:
    name: Prepare package for GitHub release
    runs-on: ubuntu-latest

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: cryptonite-${{ github.ref_name }}

      - name: Compute package digests
        run: |
          shasum -a256 "cryptonite-${{ github.ref_name }}.tar.xz" > "cryptonite-${{ github.ref_name }}.tar.xz.sha256"

      - name: Upload release artifact
        uses: actions/upload-artifact@v3
        with:
          name: cryptonite-${{ github.ref_name }}
          path: |
            cryptonite-${{ github.ref_name }}.tar.xz
            cryptonite-${{ github.ref_name }}.tar.xz.sha256
          if-no-files-found: error
          retention-days: 90
