# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Build, test and publish Cryptonite

on:
  push:
    branches: [ main, cryptonite-ci ]
    paths:
      - ".github/workflows/ci.yml"
      - ".github/workflows/lint.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

    tags:
      - 'v*.*.*'

  pull_request:
    paths:
      - ".github/workflows/ci.yml"
      - ".github/workflows/lint.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

  release:
    types: [ published ]

jobs:
  lint:
    name: Lint project
    uses: ./.github/workflows/lint.yml

  parse-release-tag:
    name: Parse release tag
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    outputs:
      release-tag: ${{ steps.get-tag.outputs.tag }}

    steps:
      - name: Get release tag
        id: get-tag
        run: |
          # Remove "v" from the tag name
          # E.g. v1.2.3 -> 1.2.3
          tag="${{ github.event.release.tag_name }}"
          echo "release-tag=${tag#v}" >> $GITHUB_OUTPUT

  make-package:
    needs: lint
    uses: ./.github/workflows/make-package.yml

  run-unit-tests:
    name: Run unit tests
    needs: make-package
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.11"]
      fail-fast: false

    uses: ./.github/workflows/run-unit-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pkg-artifact: ${{ needs.make-package.outputs.pkg-artifact }}

  run-integration-tests:
    name: Run integration tests
    needs: make-package
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7", "3.11"]
      fail-fast: false

    uses: ./.github/workflows/run-integration-tests.yml
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      pkg-artifact: ${{ needs.make-package.outputs.pkg-artifact }}

  publish-package:
    name: Publish package
    needs: [parse-release-tag, make-package, run-unit-tests, run-integration-tests]
    if: github.event_name == 'release'
    uses: ./.github/workflows/make-release.yml
    with:
      pkg-artifact: ${{ needs.make-package.outputs.pkg-artifact }}
      release-tag: ${{ needs.parse-release-tag.outputs.release-tag }}
