# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Lint project

on:
  workflow_call:

jobs:
  check-formatting:
    name: Check project formatting with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure project follows black code style
      - uses: psf/black@stable
        with:
         options: "--check --verbose --diff --color"

  run-pylint:
    name: Lint project with PyLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate requirements.txt
        run: |
          echo 'pylint>=2.6' > requirements.txt
          
          # Append Cryptonate deps to requirements.txt
          ./setup.py egg_info
          cat *.egg-info/requires.txt >> requirements.txt
          
          rm -r *.egg-info/
          

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache-dependency-path: "requirements.txt"
          cache: "pip"

      - name: Install PyLint
        run: pip3 install -r

      - name: Run PyLint
        run: |
          warnings="$(pylint --py-version='3.7' --exit-zero cryptonite/ --score=n 2>&1)"
          
          if [ -n "$warnings" ]; then
            # Escape new-lines, see: https://github.com/orgs/community/discussions/26288#discussioncomment-3251220
            warnings="${warnings//'%'/'%25'}"
            warnings="${warnings//$'\n'/'%0A'}"
            warnings="${warnings//$'\r'/'%0D'}"
          
            echo "::warning file=cryptonite, line=1, title=PyLint::$warnings"
          fi