# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Lint project

on:
  workflow_call:

jobs:
  lint-project:
    name: Lint project Black, isort and PyLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@latest
        env:
          DEFAULT_BRANCH: main

          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_MYPY: false

          LINTER_RULES_PATH: /

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
