# Copyright (C) 2022 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: Lint project

on:
  push:
    branches: [ main, cryptonite-ci ]
    paths:
      - ".github/workflows/lint.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - "cryptonite/**"
      - "pyproject.toml"
      - "setup.py"

jobs:
  check-formatting:
    name: Check project formatting with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Ensure project follows black code style
      - uses: psf/black@stable
        with:
         options: "--check --verbose --diff --color"

  run-pylint:
    name: Lint project with PyLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate requirements.txt
        run: echo 'pylint>=2.6' > requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache-dependency-path: "requirements.txt"
          cache: "pip"

      - name: Install PyLint
        run: pip3 install -r requirements.txt

      - name: Run PyLint
        run: pylint cryptonite/